#!/usr/bin/env python3
"""
repo_cleanup.py — reconcile nsheetzdesign GitHub repos against the Notion
"Website Leads" manifest, classify each repo, and archive/delete the throwaway
preview sites generated by the (now-decommissioned) lead-gen website engine.

Subcommands:
  classify              Pull repos (gh) + Notion Website Leads (REST), join on
                        repo URL, classify KEEP/DELETE/REVIEW, write
                        repo-decisions.csv. Prints summary counts.
  apply --execute       Read repo-decisions.csv and ARCHIVE every DELETE row.
        --execute --delete   ... DELETE instead of archive (irreversible).
                        Tests ONE repo, then prompts before the batch.
                        Writes repo-decisions.json as the rollback manifest.

Rules baked in:
  * PROTECT_LIST is law. A protected repo is NEVER archived or deleted, no
    matter what the CSV says.
  * Default action is ARCHIVE (reversible). Delete requires --delete.
  * Single failures never abort the batch; they are collected and reported.
  * Idempotent: repos already in the target state are skipped.
"""

import argparse
import csv
import json
import os
import re
import subprocess
import sys
import time
import urllib.request
import urllib.error

ORG = "nsheetzdesign"
CSV_PATH = "repo-decisions.csv"
JSON_PATH = "repo-decisions.json"
NOTION_DB_NAME = "Website Leads"
NOTION_VERSION = "2022-06-28"

# --- PROTECT LIST — LAW. These repos are never touched, regardless of analysis.
PROTECT_LIST = {
    "sheetzlabs-os",          # main founder-OS monorepo
    "n8n-workflows",          # n8n git-backup target (source of truth backups)
    "telosi-platform",
    "telosi-marketing",
    "holix",
    "holix-platform",
    "envision3-platform",
    "backofhouse-pro",
    "nicksheetz",             # personal website
    "saas-factory-template",
    "website-templates",      # the engine's source templates
    "Pomodoro",
}

# A generated preview repo looks like "<business-slug>-preview-<hash>".
PREVIEW_RE = re.compile(r"-preview-[0-9a-z]{3,8}$", re.IGNORECASE)

GITHUB_URL_RE = re.compile(r"github\.com/([A-Za-z0-9_.-]+)/([A-Za-z0-9_.-]+)", re.IGNORECASE)

CSV_FIELDS = ["repo", "url", "decision", "reason", "diskUsage", "isArchived", "notion_matched"]


# --------------------------------------------------------------------------- #
# helpers
# --------------------------------------------------------------------------- #
def run(cmd, check=True, capture=True):
    """Echo and run a command."""
    print("$ " + " ".join(cmd), file=sys.stderr)
    return subprocess.run(cmd, check=check, capture_output=capture, text=True)


def is_preview(name: str) -> bool:
    return bool(PREVIEW_RE.search(name)) or name.startswith("business-preview")


def pull_repos():
    res = run(["gh", "repo", "list", ORG, "--limit", "1000", "--json",
               "name,url,isArchived,diskUsage,description,homepageUrl,pushedAt"])
    return json.loads(res.stdout)


# --------------------------------------------------------------------------- #
# Notion
# --------------------------------------------------------------------------- #
def notion_request(path, token, payload=None):
    url = "https://api.notion.com/v1/" + path
    data = json.dumps(payload).encode() if payload is not None else None
    req = urllib.request.Request(url, data=data, method="POST" if data is not None else "GET")
    req.add_header("Authorization", f"Bearer {token}")
    req.add_header("Notion-Version", NOTION_VERSION)
    req.add_header("Content-Type", "application/json")
    try:
        with urllib.request.urlopen(req, timeout=30) as r:
            return json.loads(r.read().decode())
    except urllib.error.HTTPError as e:
        body = e.read().decode(errors="replace")
        print(f"Notion API error {e.code}: {body}", file=sys.stderr)
        raise


def find_database(token):
    payload = {"query": NOTION_DB_NAME,
               "filter": {"value": "database", "property": "object"}}
    res = notion_request("search", token, payload)
    results = res.get("results", [])
    # exact title match first
    def title_of(db):
        parts = db.get("title", [])
        return "".join(p.get("plain_text", "") for p in parts).strip()
    for db in results:
        if title_of(db).lower() == NOTION_DB_NAME.lower():
            return db["id"], title_of(db)
    if results:  # fall back to first database returned by the search
        return results[0]["id"], title_of(results[0])
    return None, None


def _strings_from_property(prop):
    """Yield any string-ish values out of a Notion property value."""
    t = prop.get("type")
    v = prop.get(t)
    if v is None:
        return
    if t == "url":
        yield v
    elif t in ("rich_text", "title"):
        for span in v:
            yield span.get("plain_text", "")
    elif t == "formula":
        if v.get("type") == "string" and v.get("string"):
            yield v["string"]
        if v.get("type") == "url" and v.get("url"):
            yield v["url"]
    elif t == "rollup":
        for item in v.get("array", []):
            yield from _strings_from_property({"type": item.get("type"), item.get("type"): item.get(item.get("type"))})
    elif isinstance(v, str):
        yield v


def pull_notion_repos(token, db_id):
    """Return (repo_names_set, repo_urls_set) referenced anywhere in the DB rows."""
    names, urls = set(), set()
    cursor = None
    rows = 0
    while True:
        payload = {"page_size": 100}
        if cursor:
            payload["start_cursor"] = cursor
        res = notion_request(f"databases/{db_id}/query", token, payload)
        for page in res.get("results", []):
            rows += 1
            for prop in page.get("properties", {}).values():
                for s in _strings_from_property(prop):
                    if not s:
                        continue
                    for m in GITHUB_URL_RE.finditer(s):
                        owner, repo = m.group(1), m.group(2)
                        repo = repo[:-4] if repo.endswith(".git") else repo
                        names.add(repo.lower())
                        urls.add(f"https://github.com/{owner}/{repo}".lower())
        if res.get("has_more"):
            cursor = res.get("next_cursor")
        else:
            break
    return names, urls, rows


# --------------------------------------------------------------------------- #
# classify
# --------------------------------------------------------------------------- #
def classify():
    token = os.environ.get("NOTION_TOKEN")
    if not token:
        print("ERROR: NOTION_TOKEN not set in environment.", file=sys.stderr)
        sys.exit(3)

    repos = pull_repos()
    print(f"GitHub repos pulled: {len(repos)}", file=sys.stderr)

    db_id, db_title = find_database(token)
    if not db_id:
        print(f"ERROR: Notion integration cannot see a '{NOTION_DB_NAME}' database. "
              f"Share the integration with that DB and retry.", file=sys.stderr)
        sys.exit(2)
    print(f"Notion DB: '{db_title}' ({db_id})", file=sys.stderr)

    n_names, n_urls, n_rows = pull_notion_repos(token, db_id)
    print(f"Notion rows: {n_rows}; github repo refs found: {len(n_names)}", file=sys.stderr)
    if n_rows == 0:
        print("ERROR: Notion pull returned 0 rows — integration likely not shared "
              "with the Website Leads DB. Stopping; share it and retry.", file=sys.stderr)
        sys.exit(2)

    rows_out = []
    counts = {"KEEP": 0, "DELETE": 0, "REVIEW": 0}
    for r in repos:
        name = r["name"]
        url = (r.get("url") or "").lower()
        matched = name.lower() in n_names or url in n_urls

        if name in PROTECT_LIST:
            decision, reason = "KEEP", "protected (law)"
        elif is_preview(name):
            decision = "DELETE"
            reason = "preview-style name" + (" + Notion-tracked" if matched else "")
        elif matched:
            decision, reason = "DELETE", "tracked Website-Leads preview (Notion match)"
        else:
            decision, reason = "REVIEW", "no Notion match, no preview-style name"

        counts[decision] += 1
        rows_out.append({
            "repo": name,
            "url": r.get("url", ""),
            "decision": decision,
            "reason": reason,
            "diskUsage": r.get("diskUsage", 0),
            "isArchived": r.get("isArchived", False),
            "notion_matched": matched,
        })

    rows_out.sort(key=lambda x: (x["decision"], x["repo"]))
    with open(CSV_PATH, "w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=CSV_FIELDS)
        w.writeheader()
        w.writerows(rows_out)

    total = len(rows_out)
    print(f"\n=== classify summary ===")
    print(f"total : {total}")
    print(f"KEEP  : {counts['KEEP']}")
    print(f"DELETE: {counts['DELETE']}")
    print(f"REVIEW: {counts['REVIEW']}")
    print(f"\nWrote {CSV_PATH}")


# --------------------------------------------------------------------------- #
# apply
# --------------------------------------------------------------------------- #
def read_csv():
    with open(CSV_PATH) as f:
        return list(csv.DictReader(f))


def repo_is_archived(name):
    res = run(["gh", "repo", "view", f"{ORG}/{name}", "--json", "isArchived"],
              check=False)
    if res.returncode != 0:
        return None  # likely 404 / gone
    try:
        return json.loads(res.stdout).get("isArchived", False)
    except Exception:
        return None


def do_archive(name):
    return run(["gh", "api", "--method", "PATCH", f"repos/{ORG}/{name}",
                "-F", "archived=true"], check=False)


def do_delete(name):
    return run(["gh", "repo", "delete", f"{ORG}/{name}", "--yes"], check=False)


def is_rate_limited(res):
    blob = (res.stdout or "") + (res.stderr or "")
    return "rate limit" in blob.lower() or "API rate limit exceeded" in blob


def apply(execute, delete, phase="all"):
    rows = read_csv()
    action = "DELETE" if delete else "ARCHIVE"

    # write rollback manifest BEFORE doing anything
    with open(JSON_PATH, "w") as f:
        json.dump({"action": action, "rows": rows}, f, indent=2)
    print(f"Wrote rollback manifest {JSON_PATH}", file=sys.stderr)

    targets = [r for r in rows if r["decision"].strip().upper() == "DELETE"]
    # PROTECT LIST is law — never act on a protected repo even if mislabeled.
    protected_hits = [r for r in targets if r["repo"] in PROTECT_LIST]
    if protected_hits:
        for r in protected_hits:
            print(f"REFUSING (protected): {r['repo']}", file=sys.stderr)
    targets = [r for r in targets if r["repo"] not in PROTECT_LIST]

    print(f"\n{action}: {len(targets)} repos targeted "
          f"(REVIEW rows must be resolved to KEEP/DELETE before running).")
    review_left = [r for r in rows if r["decision"].strip().upper() == "REVIEW"]
    if review_left:
        print(f"ERROR: {len(review_left)} rows still REVIEW — resolve them first.",
              file=sys.stderr)
        sys.exit(4)

    if not execute:
        print("(dry run — pass --execute to act)")
        for r in targets:
            print(f"would {action.lower()}: {r['repo']}")
        return

    if not targets:
        print("Nothing to do.")
        return

    processed = succeeded = skipped = 0
    failures = []

    def act(name):
        nonlocal processed, succeeded, skipped
        processed += 1
        if delete:
            archived = repo_is_archived(name)
            if archived is None:
                print(f"SKIP (already gone): {name}")
                skipped += 1
                return
            res = do_delete(name)
        else:
            archived = repo_is_archived(name)
            if archived is True:
                print(f"SKIP (already archived): {name}")
                skipped += 1
                return
            if archived is None:
                print(f"SKIP (not found): {name}")
                skipped += 1
                return
            res = do_archive(name)
        if res.returncode == 0:
            print(f"OK: {name}")
            succeeded += 1
        else:
            if is_rate_limited(res):
                print(f"RATE-LIMITED at {name} — pausing. Re-run to resume.",
                      file=sys.stderr)
                raise SystemExit(5)
            err = (res.stderr or res.stdout or "unknown").strip().splitlines()
            failures.append((name, err[-1] if err else "unknown"))
            print(f"FAILED: {name} — {err[-1] if err else 'unknown'}")

    # --- phase: test = act on exactly ONE repo and verify; batch = the rest ---
    if phase in ("all", "test"):
        first = targets[0]
        print(f"\n--- TEST RUN on a single repo: {first['repo']} ---")
        act(first["repo"])
        if delete:
            gone = repo_is_archived(first["repo"]) is None
            print(f"verify: {first['repo']} now {'gone' if gone else 'STILL PRESENT'}")
        else:
            print(f"verify: {first['repo']} isArchived={repo_is_archived(first['repo'])}")

    if phase == "test":
        print(f"\nTEST phase done. {len(targets)-1} repos remain for the batch phase.")
        _final_report(action, processed, succeeded, skipped, failures)
        return

    # batch: process every target; idempotent skips will pass over the test repo
    batch = targets if phase == "batch" else targets[1:]
    if phase == "all" and batch:
        ans = input(f"\nProceed to {action.lower()} the remaining {len(batch)} "
                    f"repos? Type YES to continue: ").strip()
        if ans != "YES":
            print("Aborted by operator after test run. No further repos touched.")
            _final_report(action, processed, succeeded, skipped, failures)
            return
    for r in batch:
        act(r["repo"])

    _final_report(action, processed, succeeded, skipped, failures)


def _final_report(action, processed, succeeded, skipped, failures):
    print(f"\n=== {action} report ===")
    print(f"processed: {processed}")
    print(f"succeeded: {succeeded}")
    print(f"skipped  : {skipped}")
    print(f"failed   : {len(failures)}")
    for name, err in failures:
        print(f"  FAILED {name}: {err}")
    print(f"rollback manifest: {JSON_PATH}")


# --------------------------------------------------------------------------- #
def main():
    p = argparse.ArgumentParser(description=__doc__)
    sub = p.add_subparsers(dest="cmd", required=True)
    sub.add_parser("classify")
    ap = sub.add_parser("apply")
    ap.add_argument("--execute", action="store_true")
    ap.add_argument("--delete", action="store_true")
    ap.add_argument("--phase", choices=["all", "test", "batch"], default="all")
    args = p.parse_args()

    if args.cmd == "classify":
        classify()
    elif args.cmd == "apply":
        apply(args.execute, args.delete, args.phase)


if __name__ == "__main__":
    main()
