import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Outlet, Link } from "react-router";
import { Github, Twitter, Mail } from "lucide-react";
function Nav() {
    return (_jsx("header", { className: "fixed top-0 left-0 right-0 z-50 border-b border-surface-2/50 bg-surface-0/80 backdrop-blur-md", children: _jsxs("div", { className: "mx-auto flex max-w-6xl items-center justify-between px-6 py-4", children: [_jsxs(Link, { to: "/", className: "flex items-center gap-2", children: [_jsx("div", { className: "h-6 w-6 rounded bg-brand" }), _jsx("span", { className: "font-semibold tracking-tight", children: "Sheetz Labs" })] }), _jsxs("nav", { className: "hidden items-center gap-8 text-sm text-zinc-400 md:flex", children: [_jsx("a", { href: "#products", className: "transition-colors hover:text-white", children: "Products" }), _jsx("a", { href: "#principles", className: "transition-colors hover:text-white", children: "About" }), _jsx("a", { href: "#build", className: "transition-colors hover:text-white", children: "Labs" })] }), _jsxs("a", { href: "mailto:nick@sheetzlabs.com", className: "flex items-center gap-2 rounded-lg border border-brand/30 bg-brand/10 px-4 py-2 text-sm font-medium text-brand transition-colors hover:bg-brand/20", children: [_jsx(Mail, { className: "h-4 w-4" }), "Contact"] })] }) }));
}
function Footer() {
    return (_jsx("footer", { className: "border-t border-surface-2/50 bg-surface-0", children: _jsxs("div", { className: "mx-auto flex max-w-6xl items-center justify-between px-6 py-8", children: [_jsxs("div", { className: "flex items-center gap-2", children: [_jsx("div", { className: "h-5 w-5 rounded bg-brand" }), _jsx("span", { className: "text-sm text-zinc-400", children: "\u00A9 2026 Sheetz Labs. All rights reserved." })] }), _jsxs("div", { className: "flex items-center gap-4", children: [_jsx("a", { href: "https://github.com/nsheetzdesign", target: "_blank", rel: "noopener noreferrer", className: "text-zinc-500 transition-colors hover:text-white", "aria-label": "GitHub", children: _jsx(Github, { className: "h-5 w-5" }) }), _jsx("a", { href: "https://twitter.com/nsheetzdesign", target: "_blank", rel: "noopener noreferrer", className: "text-zinc-500 transition-colors hover:text-white", "aria-label": "Twitter", children: _jsx(Twitter, { className: "h-5 w-5" }) })] })] }) }));
}
export default function MarketingLayout() {
    return (_jsxs("div", { className: "relative min-h-screen", children: [_jsx("div", { className: "gradient-orb" }), _jsx("div", { className: "grid-bg fixed inset-0 z-0" }), _jsxs("div", { className: "relative z-10", children: [_jsx(Nav, {}), _jsx("main", { className: "pt-16", children: _jsx(Outlet, {}) }), _jsx(Footer, {})] })] }));
}
