import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useLoaderData, Form, Link, useNavigation } from "react-router";
import { ArrowLeft, Linkedin, Clock, CheckCircle, XCircle, FileText } from "lucide-react";
import { Header } from "~/components/dashboard/Header";
import { getSupabaseClient } from "~/lib/supabase.server";
import { Button } from "~/components/ui/Button";
const STATUS_META = {
    draft: { color: "text-zinc-400 bg-zinc-500/10 border-zinc-500/20", label: "Draft", Icon: FileText },
    scheduled: { color: "text-blue-400 bg-blue-500/10 border-blue-500/20", label: "Scheduled", Icon: Clock },
    posted: { color: "text-green-400 bg-green-500/10 border-green-500/20", label: "Posted", Icon: CheckCircle },
    failed: { color: "text-red-400 bg-red-500/10 border-red-500/20", label: "Failed", Icon: XCircle },
};
function formatDateTime(str) {
    if (!str)
        return "—";
    return new Date(str).toLocaleString(undefined, {
        month: "short",
        day: "numeric",
        hour: "2-digit",
        minute: "2-digit",
    });
}
export async function loader({ request, context }) {
    const supabase = getSupabaseClient(context.cloudflare.env);
    const url = new URL(request.url);
    const statusFilter = url.searchParams.get("status") || "";
    let query = supabase
        .from("content_queue")
        .select("*")
        .order("scheduled_for", { ascending: true, nullsFirst: false });
    if (statusFilter)
        query = query.eq("status", statusFilter);
    const { data } = await query;
    const queue = data ?? [];
    const counts = {
        draft: queue.filter((i) => i.status === "draft").length,
        scheduled: queue.filter((i) => i.status === "scheduled").length,
        posted: queue.filter((i) => i.status === "posted").length,
        failed: queue.filter((i) => i.status === "failed").length,
    };
    return { queue, counts, statusFilter };
}
export async function action({ request, context }) {
    const supabase = getSupabaseClient(context.cloudflare.env);
    const formData = await request.formData();
    const intent = formData.get("intent");
    const id = formData.get("id");
    if (intent === "schedule") {
        await supabase
            .from("content_queue")
            .update({ status: "scheduled", scheduled_for: formData.get("scheduled_for") })
            .eq("id", id);
    }
    if (intent === "post") {
        // Trigger via API
        const apiUrl = "https://api.sheetzlabs.com";
        await fetch(`${apiUrl}/agents/content/queue/${id}/post`, { method: "POST" });
    }
    if (intent === "delete") {
        await supabase.from("content_queue").delete().eq("id", id);
    }
    return null;
}
export default function ContentQueue() {
    const { queue, counts, statusFilter } = useLoaderData();
    const navigation = useNavigation();
    const STATUSES = ["draft", "scheduled", "posted", "failed"];
    return (_jsxs("div", { className: "flex flex-1 flex-col", children: [_jsx(Header, { title: "Content Queue" }), _jsxs("main", { className: "flex-1 p-6", children: [_jsxs(Link, { to: "/dashboard/agents", className: "mb-4 inline-flex items-center gap-1.5 text-xs text-zinc-600 hover:text-zinc-300 transition-colors", children: [_jsx(ArrowLeft, { className: "h-3.5 w-3.5" }), "Departments"] }), _jsx("div", { className: "mb-6 flex flex-wrap gap-2", children: [
                            { value: "", label: `All (${queue.length})` },
                            { value: "draft", label: `Draft (${counts.draft})` },
                            { value: "scheduled", label: `Scheduled (${counts.scheduled})` },
                            { value: "posted", label: `Posted (${counts.posted})` },
                            { value: "failed", label: `Failed (${counts.failed})` },
                        ].map(({ value, label }) => (_jsx(Link, { to: value ? `?status=${value}` : "?", className: `rounded-lg border px-3 py-1.5 text-sm transition-colors ${statusFilter === value
                                ? "border-brand/50 bg-brand/10 text-brand"
                                : "border-surface-2/50 bg-surface-1/40 text-zinc-500 hover:text-zinc-300"}`, children: label }, value))) }), queue.length === 0 ? (_jsxs("div", { className: "flex flex-col items-center gap-2 rounded-xl border border-surface-2/50 bg-surface-1/40 py-16", children: [_jsx(Linkedin, { className: "h-8 w-8 text-zinc-700" }), _jsx("p", { className: "text-sm text-zinc-600", children: "No content in queue" }), _jsx("p", { className: "text-xs text-zinc-700", children: "Content is generated by the LinkedIn Scheduler agent." })] })) : (_jsx("div", { className: "space-y-3", children: queue.map((item) => {
                            const sm = STATUS_META[item.status ?? "draft"] ?? STATUS_META.draft;
                            const StatusIcon = sm.Icon;
                            return (_jsxs("div", { className: "rounded-xl border border-surface-2/50 bg-surface-1/40 p-4 backdrop-blur-sm", children: [_jsxs("div", { className: "flex flex-wrap items-start justify-between gap-3", children: [_jsxs("div", { className: "flex items-center gap-2", children: [_jsx("div", { className: "flex h-7 w-7 items-center justify-center rounded-full bg-blue-500/10", children: _jsx(Linkedin, { className: "h-4 w-4 text-blue-400" }) }), _jsxs("span", { className: `inline-flex items-center gap-1 rounded border px-2 py-0.5 text-xs font-medium ${sm.color}`, children: [_jsx(StatusIcon, { className: "h-3 w-3" }), sm.label] }), item.scheduled_for && item.status === "scheduled" && (_jsxs("span", { className: "text-xs text-zinc-500", children: ["\u2192 ", formatDateTime(item.scheduled_for)] })), item.posted_at && (_jsxs("span", { className: "text-xs text-zinc-500", children: ["posted ", formatDateTime(item.posted_at)] }))] }), _jsxs("div", { className: "flex gap-2", children: [item.status === "draft" && (_jsxs(Form, { method: "post", className: "inline-flex", children: [_jsx("input", { type: "hidden", name: "id", value: item.id }), _jsx("input", { type: "hidden", name: "intent", value: "post" }), _jsx(Button, { type: "submit", variant: "secondary", disabled: navigation.state === "submitting", children: "Post Now" })] })), (item.status === "draft" || item.status === "failed") && (_jsxs(Form, { method: "post", className: "inline-flex", children: [_jsx("input", { type: "hidden", name: "id", value: item.id }), _jsx("input", { type: "hidden", name: "intent", value: "delete" }), _jsx(Button, { type: "submit", variant: "secondary", disabled: navigation.state === "submitting", children: "Delete" })] }))] })] }), _jsx("div", { className: "mt-3", children: _jsx("p", { className: "whitespace-pre-wrap text-sm text-zinc-300 leading-relaxed", children: item.content }) }), item.external_id && (_jsxs("p", { className: "mt-2 font-mono text-xs text-zinc-600", children: ["ID: ", item.external_id] }))] }, item.id));
                        }) }))] })] }));
}
