import type { ActionFunctionArgs, LoaderFunctionArgs, MetaFunction } from "react-router";
export declare const meta: MetaFunction<typeof loader>;
export declare function loader({ params, context }: LoaderFunctionArgs): Promise<{
    email: {
        account_id: string | null;
        ai_category: string | null;
        ai_priority: string | null;
        ai_summary: string | null;
        attachment_count: number | null;
        bcc_emails: string[] | null;
        body_html: string | null;
        body_text: string | null;
        cc_emails: string[] | null;
        created_at: string | null;
        external_id: string;
        folder: string | null;
        from_email: string | null;
        from_name: string | null;
        has_attachments: boolean | null;
        id: string;
        is_archived: boolean | null;
        is_draft: boolean | null;
        is_read: boolean | null;
        is_spam: boolean | null;
        is_starred: boolean | null;
        is_trashed: boolean | null;
        labels: string[] | null;
        received_at: string | null;
        relationship_id: string | null;
        snippet: string | null;
        snoozed_until: string | null;
        subject: string | null;
        thread_id: string | null;
        to_emails: string[] | null;
        triage_category: string | null;
        triage_confidence: number | null;
        triaged_at: string | null;
        email_accounts: {
            email: string;
        } | null;
        relationships: {
            id: string;
            name: string;
            company: string | null;
        } | null;
    };
    thread: unknown[];
}>;
export declare function action({ request, params, context }: ActionFunctionArgs): Promise<Response>;
export default function EmailDetail(): import("react/jsx-runtime").JSX.Element;
