// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/auth/login": {
    params: {};
  };
  "/auth/logout": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/dashboard/ventures": {
    params: {};
  };
  "/dashboard/ventures/new": {
    params: {};
  };
  "/dashboard/ventures/:slug": {
    params: {
      "slug": string;
    };
  };
  "/dashboard/ventures/:slug/stack": {
    params: {
      "slug": string;
    };
  };
  "/dashboard/ventures/:slug/links": {
    params: {
      "slug": string;
    };
  };
  "/dashboard/ventures/:slug/roadmap": {
    params: {
      "slug": string;
    };
  };
  "/dashboard/ventures/:slug/tickets": {
    params: {
      "slug": string;
    };
  };
  "/dashboard/ventures/:slug/tasks": {
    params: {
      "slug": string;
    };
  };
  "/dashboard/ventures/:slug/docs": {
    params: {
      "slug": string;
    };
  };
  "/dashboard/pipeline": {
    params: {};
  };
  "/dashboard/pipeline/new": {
    params: {};
  };
  "/dashboard/pipeline/:id": {
    params: {
      "id": string;
    };
  };
  "/dashboard/revenue": {
    params: {};
  };
  "/dashboard/revenue/new": {
    params: {};
  };
  "/dashboard/expenses": {
    params: {};
  };
  "/dashboard/expenses/new": {
    params: {};
  };
  "/dashboard/expenses/:id": {
    params: {
      "id": string;
    };
  };
  "/dashboard/tickets": {
    params: {};
  };
  "/dashboard/relationships": {
    params: {};
  };
  "/dashboard/relationships/new": {
    params: {};
  };
  "/dashboard/relationships/:id": {
    params: {
      "id": string;
    };
  };
  "/dashboard/tasks": {
    params: {};
  };
  "/dashboard/tasks/new": {
    params: {};
  };
  "/dashboard/tasks/:id": {
    params: {
      "id": string;
    };
  };
  "/dashboard/knowledge": {
    params: {};
  };
  "/dashboard/knowledge/new": {
    params: {};
  };
  "/dashboard/knowledge/:slug": {
    params: {
      "slug": string;
    };
  };
  "/dashboard/agents": {
    params: {};
  };
  "/dashboard/agents/runs": {
    params: {};
  };
  "/dashboard/agents/runs/:id": {
    params: {
      "id": string;
    };
  };
  "/dashboard/agents/content": {
    params: {};
  };
  "/dashboard/agents/:slug": {
    params: {
      "slug": string;
    };
  };
  "/dashboard/settings": {
    params: {};
  };
  "/dashboard/settings/stripe": {
    params: {};
  };
  "/dashboard/settings/expenses": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/auth/login" | "/auth/logout" | "/dashboard" | "/dashboard/ventures" | "/dashboard/ventures/new" | "/dashboard/ventures/:slug" | "/dashboard/ventures/:slug/stack" | "/dashboard/ventures/:slug/links" | "/dashboard/ventures/:slug/roadmap" | "/dashboard/ventures/:slug/tickets" | "/dashboard/ventures/:slug/tasks" | "/dashboard/ventures/:slug/docs" | "/dashboard/pipeline" | "/dashboard/pipeline/new" | "/dashboard/pipeline/:id" | "/dashboard/revenue" | "/dashboard/revenue/new" | "/dashboard/expenses" | "/dashboard/expenses/new" | "/dashboard/expenses/:id" | "/dashboard/tickets" | "/dashboard/relationships" | "/dashboard/relationships/new" | "/dashboard/relationships/:id" | "/dashboard/tasks" | "/dashboard/tasks/new" | "/dashboard/tasks/:id" | "/dashboard/knowledge" | "/dashboard/knowledge/new" | "/dashboard/knowledge/:slug" | "/dashboard/agents" | "/dashboard/agents/runs" | "/dashboard/agents/runs/:id" | "/dashboard/agents/content" | "/dashboard/agents/:slug" | "/dashboard/settings" | "/dashboard/settings/stripe" | "/dashboard/settings/expenses";
  };
  "routes/_marketing.tsx": {
    id: "routes/_marketing";
    page: "/";
  };
  "routes/_marketing._index.tsx": {
    id: "routes/_marketing._index";
    page: "/";
  };
  "routes/auth.login.tsx": {
    id: "routes/auth.login";
    page: "/auth/login";
  };
  "routes/auth.logout.tsx": {
    id: "routes/auth.logout";
    page: "/auth/logout";
  };
  "routes/dashboard.tsx": {
    id: "routes/dashboard";
    page: "/dashboard" | "/dashboard/ventures" | "/dashboard/ventures/new" | "/dashboard/ventures/:slug" | "/dashboard/ventures/:slug/stack" | "/dashboard/ventures/:slug/links" | "/dashboard/ventures/:slug/roadmap" | "/dashboard/ventures/:slug/tickets" | "/dashboard/ventures/:slug/tasks" | "/dashboard/ventures/:slug/docs" | "/dashboard/pipeline" | "/dashboard/pipeline/new" | "/dashboard/pipeline/:id" | "/dashboard/revenue" | "/dashboard/revenue/new" | "/dashboard/expenses" | "/dashboard/expenses/new" | "/dashboard/expenses/:id" | "/dashboard/tickets" | "/dashboard/relationships" | "/dashboard/relationships/new" | "/dashboard/relationships/:id" | "/dashboard/tasks" | "/dashboard/tasks/new" | "/dashboard/tasks/:id" | "/dashboard/knowledge" | "/dashboard/knowledge/new" | "/dashboard/knowledge/:slug" | "/dashboard/agents" | "/dashboard/agents/runs" | "/dashboard/agents/runs/:id" | "/dashboard/agents/content" | "/dashboard/agents/:slug" | "/dashboard/settings" | "/dashboard/settings/stripe" | "/dashboard/settings/expenses";
  };
  "routes/dashboard._index.tsx": {
    id: "routes/dashboard._index";
    page: "/dashboard";
  };
  "routes/dashboard.ventures.tsx": {
    id: "routes/dashboard.ventures";
    page: "/dashboard/ventures" | "/dashboard/ventures/new" | "/dashboard/ventures/:slug" | "/dashboard/ventures/:slug/stack" | "/dashboard/ventures/:slug/links" | "/dashboard/ventures/:slug/roadmap" | "/dashboard/ventures/:slug/tickets" | "/dashboard/ventures/:slug/tasks" | "/dashboard/ventures/:slug/docs";
  };
  "routes/dashboard.ventures._index.tsx": {
    id: "routes/dashboard.ventures._index";
    page: "/dashboard/ventures";
  };
  "routes/dashboard.ventures.new.tsx": {
    id: "routes/dashboard.ventures.new";
    page: "/dashboard/ventures/new";
  };
  "routes/dashboard.ventures.$slug.tsx": {
    id: "routes/dashboard.ventures.$slug";
    page: "/dashboard/ventures/:slug" | "/dashboard/ventures/:slug/stack" | "/dashboard/ventures/:slug/links" | "/dashboard/ventures/:slug/roadmap" | "/dashboard/ventures/:slug/tickets" | "/dashboard/ventures/:slug/tasks" | "/dashboard/ventures/:slug/docs";
  };
  "routes/dashboard.ventures.$slug._index.tsx": {
    id: "routes/dashboard.ventures.$slug._index";
    page: "/dashboard/ventures/:slug";
  };
  "routes/dashboard.ventures.$slug.stack.tsx": {
    id: "routes/dashboard.ventures.$slug.stack";
    page: "/dashboard/ventures/:slug/stack";
  };
  "routes/dashboard.ventures.$slug.links.tsx": {
    id: "routes/dashboard.ventures.$slug.links";
    page: "/dashboard/ventures/:slug/links";
  };
  "routes/dashboard.ventures.$slug.roadmap.tsx": {
    id: "routes/dashboard.ventures.$slug.roadmap";
    page: "/dashboard/ventures/:slug/roadmap";
  };
  "routes/dashboard.ventures.$slug.tickets.tsx": {
    id: "routes/dashboard.ventures.$slug.tickets";
    page: "/dashboard/ventures/:slug/tickets";
  };
  "routes/dashboard.ventures.$slug.tasks.tsx": {
    id: "routes/dashboard.ventures.$slug.tasks";
    page: "/dashboard/ventures/:slug/tasks";
  };
  "routes/dashboard.ventures.$slug.docs.tsx": {
    id: "routes/dashboard.ventures.$slug.docs";
    page: "/dashboard/ventures/:slug/docs";
  };
  "routes/dashboard.pipeline.tsx": {
    id: "routes/dashboard.pipeline";
    page: "/dashboard/pipeline" | "/dashboard/pipeline/new" | "/dashboard/pipeline/:id";
  };
  "routes/dashboard.pipeline._index.tsx": {
    id: "routes/dashboard.pipeline._index";
    page: "/dashboard/pipeline";
  };
  "routes/dashboard.pipeline.new.tsx": {
    id: "routes/dashboard.pipeline.new";
    page: "/dashboard/pipeline/new";
  };
  "routes/dashboard.pipeline.$id.tsx": {
    id: "routes/dashboard.pipeline.$id";
    page: "/dashboard/pipeline/:id";
  };
  "routes/dashboard.revenue.tsx": {
    id: "routes/dashboard.revenue";
    page: "/dashboard/revenue" | "/dashboard/revenue/new";
  };
  "routes/dashboard.revenue._index.tsx": {
    id: "routes/dashboard.revenue._index";
    page: "/dashboard/revenue";
  };
  "routes/dashboard.revenue.new.tsx": {
    id: "routes/dashboard.revenue.new";
    page: "/dashboard/revenue/new";
  };
  "routes/dashboard.expenses.tsx": {
    id: "routes/dashboard.expenses";
    page: "/dashboard/expenses" | "/dashboard/expenses/new" | "/dashboard/expenses/:id";
  };
  "routes/dashboard.expenses._index.tsx": {
    id: "routes/dashboard.expenses._index";
    page: "/dashboard/expenses";
  };
  "routes/dashboard.expenses.new.tsx": {
    id: "routes/dashboard.expenses.new";
    page: "/dashboard/expenses/new";
  };
  "routes/dashboard.expenses.$id.tsx": {
    id: "routes/dashboard.expenses.$id";
    page: "/dashboard/expenses/:id";
  };
  "routes/dashboard.tickets.tsx": {
    id: "routes/dashboard.tickets";
    page: "/dashboard/tickets";
  };
  "routes/dashboard.tickets._index.tsx": {
    id: "routes/dashboard.tickets._index";
    page: "/dashboard/tickets";
  };
  "routes/dashboard.relationships.tsx": {
    id: "routes/dashboard.relationships";
    page: "/dashboard/relationships" | "/dashboard/relationships/new" | "/dashboard/relationships/:id";
  };
  "routes/dashboard.relationships._index.tsx": {
    id: "routes/dashboard.relationships._index";
    page: "/dashboard/relationships";
  };
  "routes/dashboard.relationships.new.tsx": {
    id: "routes/dashboard.relationships.new";
    page: "/dashboard/relationships/new";
  };
  "routes/dashboard.relationships.$id.tsx": {
    id: "routes/dashboard.relationships.$id";
    page: "/dashboard/relationships/:id";
  };
  "routes/dashboard.tasks.tsx": {
    id: "routes/dashboard.tasks";
    page: "/dashboard/tasks" | "/dashboard/tasks/new" | "/dashboard/tasks/:id";
  };
  "routes/dashboard.tasks._index.tsx": {
    id: "routes/dashboard.tasks._index";
    page: "/dashboard/tasks";
  };
  "routes/dashboard.tasks.new.tsx": {
    id: "routes/dashboard.tasks.new";
    page: "/dashboard/tasks/new";
  };
  "routes/dashboard.tasks.$id.tsx": {
    id: "routes/dashboard.tasks.$id";
    page: "/dashboard/tasks/:id";
  };
  "routes/dashboard.knowledge.tsx": {
    id: "routes/dashboard.knowledge";
    page: "/dashboard/knowledge" | "/dashboard/knowledge/new" | "/dashboard/knowledge/:slug";
  };
  "routes/dashboard.knowledge._index.tsx": {
    id: "routes/dashboard.knowledge._index";
    page: "/dashboard/knowledge";
  };
  "routes/dashboard.knowledge.new.tsx": {
    id: "routes/dashboard.knowledge.new";
    page: "/dashboard/knowledge/new";
  };
  "routes/dashboard.knowledge.$slug.tsx": {
    id: "routes/dashboard.knowledge.$slug";
    page: "/dashboard/knowledge/:slug";
  };
  "routes/dashboard.agents.tsx": {
    id: "routes/dashboard.agents";
    page: "/dashboard/agents" | "/dashboard/agents/runs" | "/dashboard/agents/runs/:id" | "/dashboard/agents/content" | "/dashboard/agents/:slug";
  };
  "routes/dashboard.agents._index.tsx": {
    id: "routes/dashboard.agents._index";
    page: "/dashboard/agents";
  };
  "routes/dashboard.agents.runs.tsx": {
    id: "routes/dashboard.agents.runs";
    page: "/dashboard/agents/runs" | "/dashboard/agents/runs/:id";
  };
  "routes/dashboard.agents.runs._index.tsx": {
    id: "routes/dashboard.agents.runs._index";
    page: "/dashboard/agents/runs";
  };
  "routes/dashboard.agents.runs.$id.tsx": {
    id: "routes/dashboard.agents.runs.$id";
    page: "/dashboard/agents/runs/:id";
  };
  "routes/dashboard.agents.content.tsx": {
    id: "routes/dashboard.agents.content";
    page: "/dashboard/agents/content";
  };
  "routes/dashboard.agents.$slug.tsx": {
    id: "routes/dashboard.agents.$slug";
    page: "/dashboard/agents/:slug";
  };
  "routes/dashboard.settings.tsx": {
    id: "routes/dashboard.settings";
    page: "/dashboard/settings" | "/dashboard/settings/stripe" | "/dashboard/settings/expenses";
  };
  "routes/dashboard.settings.stripe.tsx": {
    id: "routes/dashboard.settings.stripe";
    page: "/dashboard/settings/stripe";
  };
  "routes/dashboard.settings.expenses.tsx": {
    id: "routes/dashboard.settings.expenses";
    page: "/dashboard/settings/expenses";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/_marketing": typeof import("./app/routes/_marketing.tsx");
  "routes/_marketing._index": typeof import("./app/routes/_marketing._index.tsx");
  "routes/auth.login": typeof import("./app/routes/auth.login.tsx");
  "routes/auth.logout": typeof import("./app/routes/auth.logout.tsx");
  "routes/dashboard": typeof import("./app/routes/dashboard.tsx");
  "routes/dashboard._index": typeof import("./app/routes/dashboard._index.tsx");
  "routes/dashboard.ventures": typeof import("./app/routes/dashboard.ventures.tsx");
  "routes/dashboard.ventures._index": typeof import("./app/routes/dashboard.ventures._index.tsx");
  "routes/dashboard.ventures.new": typeof import("./app/routes/dashboard.ventures.new.tsx");
  "routes/dashboard.ventures.$slug": typeof import("./app/routes/dashboard.ventures.$slug.tsx");
  "routes/dashboard.ventures.$slug._index": typeof import("./app/routes/dashboard.ventures.$slug._index.tsx");
  "routes/dashboard.ventures.$slug.stack": typeof import("./app/routes/dashboard.ventures.$slug.stack.tsx");
  "routes/dashboard.ventures.$slug.links": typeof import("./app/routes/dashboard.ventures.$slug.links.tsx");
  "routes/dashboard.ventures.$slug.roadmap": typeof import("./app/routes/dashboard.ventures.$slug.roadmap.tsx");
  "routes/dashboard.ventures.$slug.tickets": typeof import("./app/routes/dashboard.ventures.$slug.tickets.tsx");
  "routes/dashboard.ventures.$slug.tasks": typeof import("./app/routes/dashboard.ventures.$slug.tasks.tsx");
  "routes/dashboard.ventures.$slug.docs": typeof import("./app/routes/dashboard.ventures.$slug.docs.tsx");
  "routes/dashboard.pipeline": typeof import("./app/routes/dashboard.pipeline.tsx");
  "routes/dashboard.pipeline._index": typeof import("./app/routes/dashboard.pipeline._index.tsx");
  "routes/dashboard.pipeline.new": typeof import("./app/routes/dashboard.pipeline.new.tsx");
  "routes/dashboard.pipeline.$id": typeof import("./app/routes/dashboard.pipeline.$id.tsx");
  "routes/dashboard.revenue": typeof import("./app/routes/dashboard.revenue.tsx");
  "routes/dashboard.revenue._index": typeof import("./app/routes/dashboard.revenue._index.tsx");
  "routes/dashboard.revenue.new": typeof import("./app/routes/dashboard.revenue.new.tsx");
  "routes/dashboard.expenses": typeof import("./app/routes/dashboard.expenses.tsx");
  "routes/dashboard.expenses._index": typeof import("./app/routes/dashboard.expenses._index.tsx");
  "routes/dashboard.expenses.new": typeof import("./app/routes/dashboard.expenses.new.tsx");
  "routes/dashboard.expenses.$id": typeof import("./app/routes/dashboard.expenses.$id.tsx");
  "routes/dashboard.tickets": typeof import("./app/routes/dashboard.tickets.tsx");
  "routes/dashboard.tickets._index": typeof import("./app/routes/dashboard.tickets._index.tsx");
  "routes/dashboard.relationships": typeof import("./app/routes/dashboard.relationships.tsx");
  "routes/dashboard.relationships._index": typeof import("./app/routes/dashboard.relationships._index.tsx");
  "routes/dashboard.relationships.new": typeof import("./app/routes/dashboard.relationships.new.tsx");
  "routes/dashboard.relationships.$id": typeof import("./app/routes/dashboard.relationships.$id.tsx");
  "routes/dashboard.tasks": typeof import("./app/routes/dashboard.tasks.tsx");
  "routes/dashboard.tasks._index": typeof import("./app/routes/dashboard.tasks._index.tsx");
  "routes/dashboard.tasks.new": typeof import("./app/routes/dashboard.tasks.new.tsx");
  "routes/dashboard.tasks.$id": typeof import("./app/routes/dashboard.tasks.$id.tsx");
  "routes/dashboard.knowledge": typeof import("./app/routes/dashboard.knowledge.tsx");
  "routes/dashboard.knowledge._index": typeof import("./app/routes/dashboard.knowledge._index.tsx");
  "routes/dashboard.knowledge.new": typeof import("./app/routes/dashboard.knowledge.new.tsx");
  "routes/dashboard.knowledge.$slug": typeof import("./app/routes/dashboard.knowledge.$slug.tsx");
  "routes/dashboard.agents": typeof import("./app/routes/dashboard.agents.tsx");
  "routes/dashboard.agents._index": typeof import("./app/routes/dashboard.agents._index.tsx");
  "routes/dashboard.agents.runs": typeof import("./app/routes/dashboard.agents.runs.tsx");
  "routes/dashboard.agents.runs._index": typeof import("./app/routes/dashboard.agents.runs._index.tsx");
  "routes/dashboard.agents.runs.$id": typeof import("./app/routes/dashboard.agents.runs.$id.tsx");
  "routes/dashboard.agents.content": typeof import("./app/routes/dashboard.agents.content.tsx");
  "routes/dashboard.agents.$slug": typeof import("./app/routes/dashboard.agents.$slug.tsx");
  "routes/dashboard.settings": typeof import("./app/routes/dashboard.settings.tsx");
  "routes/dashboard.settings.stripe": typeof import("./app/routes/dashboard.settings.stripe.tsx");
  "routes/dashboard.settings.expenses": typeof import("./app/routes/dashboard.settings.expenses.tsx");
};