import type { LoaderFunctionArgs, ActionFunctionArgs } from "react-router";
import { useLoaderData, Form, Link, useNavigation } from "react-router";
import { ArrowLeft, Linkedin, Clock, CheckCircle, XCircle, FileText } from "lucide-react";
import { Header } from "~/components/dashboard/Header";
import { getSupabaseClient } from "~/lib/supabase.server";
import { Button } from "~/components/ui/Button";

const STATUS_META: Record<string, { color: string; label: string; Icon: React.ComponentType<{ className?: string }> }> = {
  draft: { color: "text-zinc-400 bg-zinc-500/10 border-zinc-500/20", label: "Draft", Icon: FileText },
  scheduled: { color: "text-blue-400 bg-blue-500/10 border-blue-500/20", label: "Scheduled", Icon: Clock },
  posted: { color: "text-green-400 bg-green-500/10 border-green-500/20", label: "Posted", Icon: CheckCircle },
  failed: { color: "text-red-400 bg-red-500/10 border-red-500/20", label: "Failed", Icon: XCircle },
};

function formatDateTime(str: string | null) {
  if (!str) return "—";
  return new Date(str).toLocaleString(undefined, {
    month: "short",
    day: "numeric",
    hour: "2-digit",
    minute: "2-digit",
  });
}

export async function loader({ request, context }: LoaderFunctionArgs) {
  const supabase = getSupabaseClient(context.cloudflare.env);
  const url = new URL(request.url);
  const statusFilter = url.searchParams.get("status") || "";

  let query = supabase
    .from("content_queue")
    .select("*")
    .order("scheduled_for", { ascending: true, nullsFirst: false });

  if (statusFilter) query = query.eq("status", statusFilter);

  const { data } = await query;
  const queue = data ?? [];

  const counts = {
    draft: queue.filter((i) => i.status === "draft").length,
    scheduled: queue.filter((i) => i.status === "scheduled").length,
    posted: queue.filter((i) => i.status === "posted").length,
    failed: queue.filter((i) => i.status === "failed").length,
  };

  return { queue, counts, statusFilter };
}

export async function action({ request, context }: ActionFunctionArgs) {
  const supabase = getSupabaseClient(context.cloudflare.env);
  const formData = await request.formData();
  const intent = formData.get("intent");
  const id = formData.get("id") as string;

  if (intent === "schedule") {
    await supabase
      .from("content_queue")
      .update({ status: "scheduled", scheduled_for: formData.get("scheduled_for") as string })
      .eq("id", id);
  }

  if (intent === "post") {
    // Trigger via API
    const apiUrl = "https://api.sheetzlabs.com";
    await fetch(`${apiUrl}/agents/content/queue/${id}/post`, { method: "POST" });
  }

  if (intent === "delete") {
    await supabase.from("content_queue").delete().eq("id", id);
  }

  return null;
}

export default function ContentQueue() {
  const { queue, counts, statusFilter } = useLoaderData<typeof loader>();
  const navigation = useNavigation();
  const STATUSES = ["draft", "scheduled", "posted", "failed"];

  return (
    <div className="flex flex-1 flex-col">
      <Header title="Content Queue" />
      <main className="flex-1 p-6">
        <Link
          to="/dashboard/agents"
          className="mb-4 inline-flex items-center gap-1.5 text-xs text-zinc-600 hover:text-zinc-300 transition-colors"
        >
          <ArrowLeft className="h-3.5 w-3.5" />
          Departments
        </Link>

        {/* Status tabs */}
        <div className="mb-6 flex flex-wrap gap-2">
          {[
            { value: "", label: `All (${queue.length})` },
            { value: "draft", label: `Draft (${counts.draft})` },
            { value: "scheduled", label: `Scheduled (${counts.scheduled})` },
            { value: "posted", label: `Posted (${counts.posted})` },
            { value: "failed", label: `Failed (${counts.failed})` },
          ].map(({ value, label }) => (
            <Link
              key={value}
              to={value ? `?status=${value}` : "?"}
              className={`rounded-lg border px-3 py-1.5 text-sm transition-colors ${
                statusFilter === value
                  ? "border-brand/50 bg-brand/10 text-brand"
                  : "border-surface-2/50 bg-surface-1/40 text-zinc-500 hover:text-zinc-300"
              }`}
            >
              {label}
            </Link>
          ))}
        </div>

        {/* Queue items */}
        {queue.length === 0 ? (
          <div className="flex flex-col items-center gap-2 rounded-xl border border-surface-2/50 bg-surface-1/40 py-16">
            <Linkedin className="h-8 w-8 text-zinc-700" />
            <p className="text-sm text-zinc-600">No content in queue</p>
            <p className="text-xs text-zinc-700">
              Content is generated by the LinkedIn Scheduler agent.
            </p>
          </div>
        ) : (
          <div className="space-y-3">
            {queue.map((item) => {
              const sm = STATUS_META[item.status ?? "draft"] ?? STATUS_META.draft;
              const StatusIcon = sm.Icon;
              return (
                <div
                  key={item.id}
                  className="rounded-xl border border-surface-2/50 bg-surface-1/40 p-4 backdrop-blur-sm"
                >
                  <div className="flex flex-wrap items-start justify-between gap-3">
                    <div className="flex items-center gap-2">
                      <div className="flex h-7 w-7 items-center justify-center rounded-full bg-blue-500/10">
                        <Linkedin className="h-4 w-4 text-blue-400" />
                      </div>
                      <span className={`inline-flex items-center gap-1 rounded border px-2 py-0.5 text-xs font-medium ${sm.color}`}>
                        <StatusIcon className="h-3 w-3" />
                        {sm.label}
                      </span>
                      {item.scheduled_for && item.status === "scheduled" && (
                        <span className="text-xs text-zinc-500">
                          → {formatDateTime(item.scheduled_for)}
                        </span>
                      )}
                      {item.posted_at && (
                        <span className="text-xs text-zinc-500">
                          posted {formatDateTime(item.posted_at)}
                        </span>
                      )}
                    </div>

                    {/* Actions */}
                    <div className="flex gap-2">
                      {item.status === "draft" && (
                        <Form method="post" className="inline-flex">
                          <input type="hidden" name="id" value={item.id} />
                          <input type="hidden" name="intent" value="post" />
                          <Button
                            type="submit"
                            variant="secondary"
                            disabled={navigation.state === "submitting"}
                          >
                            Post Now
                          </Button>
                        </Form>
                      )}
                      {(item.status === "draft" || item.status === "failed") && (
                        <Form method="post" className="inline-flex">
                          <input type="hidden" name="id" value={item.id} />
                          <input type="hidden" name="intent" value="delete" />
                          <Button
                            type="submit"
                            variant="secondary"
                            disabled={navigation.state === "submitting"}
                          >
                            Delete
                          </Button>
                        </Form>
                      )}
                    </div>
                  </div>

                  {/* Content preview */}
                  <div className="mt-3">
                    <p className="whitespace-pre-wrap text-sm text-zinc-300 leading-relaxed">
                      {item.content}
                    </p>
                  </div>

                  {item.external_id && (
                    <p className="mt-2 font-mono text-xs text-zinc-600">
                      ID: {item.external_id}
                    </p>
                  )}
                </div>
              );
            })}
          </div>
        )}
      </main>
    </div>
  );
}
